### ISSUE TITLE
Can't use a One-Handed Weapon in the Right Hand

### ISSUE THREAD

**Issue by Andrek25** [atomicpickle/Roguelike#1]
I have found a bug where you can't use a One-Handed Weapon in the Right Hand because you get a 'Nil' atk when calculating damage, check [this line](https://github.com/atomicpickle/Roguelike/blob/main/Player.rb#L400).

Roguelike/Game_DB.rb:418:in `calc_damage_alt2': undefined method `-' for nil:NilClass (NoMethodError)

**Comment by atomicpickle** [comment]
Thanks! I've made a fix for this and it will be in the 1.0.4 beta.

Until that release is posted, simply dont have a 1 handed weapon in your right hand without one already in your left hand.

There are a couple other things I want in the next release that I'm working on so it wont be out for another 12 hours or so.
